name: Integration

on: [push]

jobs:
  codesniffer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Install dependencies
        run: composer install
      - name: Run code sniffer
        run: ./vendor/bin/phpcs